Filter-scenarios based on categories
hobbyfarm/admin-ui pull request #141
Opened 2022-11-29 12:08 UTC by abrahimi93

2022-11-29 13:40 UTC, PhPrinz requested changes

2022-11-29 13:40 UTC, PhPrinz commented on src/app/scenario/scenario.component.html
> +      <clr-dropdown-menu clrPosition="top-left" *clrIfOpen>
```suggestion
      <clr-dropdown-menu clrPosition="bottom-left" *clrIfOpen>
```

If the List of Categories has some more entries, the Dropdown List gets hidden behind the frame of the Browser Window

2022-11-29 13:40 UTC, PhPrinz commented on src/app/scenario/scenario.component.html
> +        <span *ngIf="category==''">All</span>
After selecting "All" or "No Category" the dropdown doesn't close by itself as it does with the other selectable categories. Tested with Firefox and Chrome.

2022-11-29 13:40 UTC, PhPrinz commented on src/app/scenario/scenario.component.ts
> +    console.log(c);
```suggestion
```

2022-11-29 13:40 UTC, PhPrinz commented on src/app/scenario/scenario.component.ts
> +      console.log(s);
```suggestion
```

2022-11-30 11:50 UTC, jggoebel commented on src/app/scenario/scenario.component.html
> +        <div class="dropdown-item" (click)="setCategoryFilter('')">All</div>
add 'clrDropdownItem' to close dropown after selection. Add to no Category Filter aswell

2022-11-30 12:14 UTC, jggoebel commented on src/app/scenario/scenario.component.html
> +        <div class="dropdown-item" (click)="setCategoryFilter('')" clrDropdownItem>select category</div>
"All categories" OR "All scenarios"

2022-11-30 12:14 UTC, jggoebel commented on src/app/scenario/scenario.component.html
> +        <span *ngIf="category=='__none__'">No Category</span>
"Without category"

2022-11-30 12:15 UTC, jggoebel commented on src/app/scenario/scenario.component.html
> +        <span *ngIf="category==''">All</span>
"All scenarios" OR "All categories"

2022-11-30 12:42 UTC, jggoebel commented on src/app/scenario/scenario.component.html
> +          clrDropdownItem
duplicate

2022-12-02 12:57 UTC, merged